# Generated by Django 6.0.5 on 2026-07-14 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_is_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('COMUNICADO_IFRN', 'Comunicado IFRN'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('primary_button_text', models.CharField(blank=True, max_length=60)),
                ('primary_button_link', models.CharField(blank=True, max_length=300)),
                ('secondary_button_text', models.CharField(blank=True, max_length=60)),
                ('secondary_button_link', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order'], name='feed_banner_order_830ea1_idx')],
            },
        ),
    ]
